name: nn_zoom_workshop
channels:
  - defaults
dependencies:
  - numpy=1.18.1
  - python=3.7
  - matplotlib
  - pillow
  - opencv
  - ipython
  - tqdm
  - pip
  - pytorch::pcytorch
  - pytorch::torchvision
  - pip:
    - pysimplegui
    - opencv-contrib-python==4.0.0.21
    - git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI
 
